name: bundle windows
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta
jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build gpshell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://slproweb.com/download/Win32OpenSSL-3_2_0.msi","C:\Temp\Win32OpenSSL-3_2_0.msi")      
      - name: Build gpshell
        shell: cmd
        run: |
          dir
          choco install -y doxygen.install graphviz
          C:\Temp\Win32OpenSSL-3_2_0.msi /quiet
          copy "C:\Program Files (x86)\OpenSSL-Win32\lib\VC\x86\MD\*" "C:\Program Files (x86)\OpenSSL-Win32\lib\VC"
          "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\vsdevcmd"
          cmake -G "NMake Makefiles" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -Bbuild -DOPENSSL_ROOT_DIR="C:\Program Files (x86)\OpenSSL-Win32" -DZLIB_ROOT="%cd%\zlib-1.2.8\win32-build"
          cd build
          nmake VERBOSE=1
          nmake VERBOSE=1 doc
          nmake VERBOSE=1 package
          ..\windows-bundle.bat
